CREATE DATABASE IF NOT EXISTS personas;
USE personas;

SELECT 'CREATING DATABASE STRUCTURE' as 'INFO';

DROP TABLE IF EXISTS personas;
CREATE TABLE personas(
id  int  PRIMARY KEY NOT NULL,
nombre VARCHAR(20) NOT NULL

);

SELECT 'LOADING personas' as 'INFO';