CREATE DATABASE IF NOT EXISTS campos2;
USE campos2;

SELECT 'CREATING DATABASE STRUCTURE' as 'INFO';

DROP TABLE IF EXISTS campos2;
CREATE TABLE campos2(
id  int  PRIMARY KEY NOT NULL,
nombre VARCHAR(20) NOT NULL,
ciudad VARCHAR(20) NOT NULL,
edad INT NOT NULL,
imagen VARCHAR(100) NOT NULL  

);

SELECT 'LOADING personas' as 'INFO';